import type { Candidate, Job, NewHire } from '@/lib/types';

export const candidates: Candidate[] = [
  {
    id: "CAND-001",
    name: "Alana Vasquez",
    avatarUrl: "",
    email: "alana.v@example.com",
    jobTitle: "Senior Frontend Developer",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Figma"],
    experienceLevel: "Senior",
    skillFit: 85,
    experienceFit: 90,
    status: "Interview",
    appliedDate: "2023-10-15",
  },
  {
    id: "CAND-002",
    name: "Ben Carter",
    avatarUrl: "",
    email: "ben.c@example.com",
    jobTitle: "Backend Engineer",
    skills: ["Node.js", "Python", "PostgreSQL", "Docker", "AWS"],
    experienceLevel: "Mid-level",
    skillFit: 70,
    experienceFit: 75,
    status: "Screening",
    appliedDate: "2023-10-18",
  },
  {
    id: "CAND-003",
    name: "Carla Rodriguez",
    avatarUrl: "",
    email: "carla.r@example.com",
    jobTitle: "Product Manager",
    skills: ["Agile", "JIRA", "Roadmapping", "User Research"],
    experienceLevel: "Senior",
    skillFit: 92,
    experienceFit: 95,
    status: "Offer",
    appliedDate: "2023-10-12",
  },
  {
    id: "CAND-004",
    name: "David Kim",
    avatarUrl: "",
    email: "david.k@example.com",
    jobTitle: "UX/UI Designer",
    skills: ["Figma", "Sketch", "Prototyping", "Design Systems"],
    experienceLevel: "Mid-level",
    skillFit: 98,
    experienceFit: 90,
    status: "Hired",
    appliedDate: "2023-10-05",
  },
  {
    id: "CAND-005",
    name: "Eva Chen",
    avatarUrl: "",
    email: "eva.c@example.com",
    jobTitle: "Data Scientist",
    skills: ["Python", "TensorFlow", "PyTorch", "SQL", "Scikit-learn"],
    experienceLevel: "Mid-level",
    skillFit: 40,
    experienceFit: 50,
    status: "Rejected",
    appliedDate: "2023-10-20",
  },
  {
    id: "CAND-006",
    name: "Frank Miller",
    avatarUrl: "",
    email: "frank.m@example.com",
    jobTitle: "Java Backend Developer",
    skills: ["Java", "Spring Boot", "Microservices", "Kafka"],
    experienceLevel: "Senior",
    skillFit: 60,
    experienceFit: 65,
    status: "Sourced",
    appliedDate: "2023-10-22",
  },
  {
    id: "CAND-007",
    name: "Grace Lee",
    avatarUrl: "",
    email: "grace.l@example.com",
    jobTitle: "Senior Frontend Developer",
    skills: ["React", "Redux", "Webpack", "CSS-in-JS"],
    experienceLevel: "Lead",
    skillFit: 88,
    experienceFit: 92,
    status: "Sourced",
    appliedDate: "2023-10-23",
  },
  {
    id: "CAND-008",
    name: "Henry Wilson",
    avatarUrl: "",
    email: "henry.w@example.com",
    jobTitle: "Backend Engineer",
    skills: ["Go", "gRPC", "Kubernetes", "Prometheus"],
    experienceLevel: "Entry-level",
    skillFit: 55,
    experienceFit: 45,
    status: "Screening",
    appliedDate: "2023-10-21",
  },
  {
    id: "CAND-009",
    name: "Isla Brown",
    avatarUrl: "",
    email: "isla.b@example.com",
    jobTitle: "Product Manager",
    skills: ["Market Research", "Go-to-market Strategy", "A/B Testing"],
    experienceLevel: "Mid-level",
    skillFit: 80,
    experienceFit: 70,
    status: "Interview",
    appliedDate: "2023-10-19",
  },
  {
    id: "CAND-010",
    name: "Jack Taylor",
    avatarUrl: "",
    email: "jack.t@example.com",
    jobTitle: "UX/UI Designer",
    skills: ["Adobe XD", "User Flows", "Wireframing", "Usability Testing"],
    experienceLevel: "Entry-level",
    skillFit: 65,
    experienceFit: 50,
    status: "Sourced",
    appliedDate: "2023-10-24",
  },
  {
    id: "CAND-011",
    name: "Kara Davis",
    avatarUrl: "",
    email: "kara.d@example.com",
    jobTitle: "Data Scientist",
    skills: ["R", "Spark", "Tableau", "Machine Learning"],
    experienceLevel: "Senior",
    skillFit: 75,
    experienceFit: 85,
    status: "Screening",
    appliedDate: "2023-10-22",
  },
  {
    id: "CAND-012",
    name: "Leo Garcia",
    avatarUrl: "",
    email: "leo.g@example.com",
    jobTitle: "Java Backend Developer",
    skills: ["Java", "Quarkus", "Hibernate", "MongoDB"],
    experienceLevel: "Mid-level",
    skillFit: 82,
    experienceFit: 78,
    status: "Interview",
    appliedDate: "2023-10-20",
  },
  {
    id: "CAND-013",
    name: "Mia Martinez",
    avatarUrl: "",
    email: "mia.m@example.com",
    jobTitle: "Senior Frontend Developer",
    skills: ["Vue.js", "Nuxt.js", "SASS", "Jest"],
    experienceLevel: "Senior",
    skillFit: 95,
    experienceFit: 90,
    status: "Offer",
    appliedDate: "2023-10-14",
  },
  {
    id: "CAND-014",
    name: "Noah Anderson",
    avatarUrl: "",
    email: "noah.a@example.com",
    jobTitle: "Backend Engineer",
    skills: ["Ruby on Rails", "Sidekiq", "Redis", "Heroku"],
    experienceLevel: "Mid-level",
    skillFit: 68,
    experienceFit: 72,
    status: "Sourced",
    appliedDate: "2023-10-25",
  },
  {
    id: "CAND-015",
    name: "Olivia Hernandez",
    avatarUrl: "",
    email: "olivia.h@example.com",
    jobTitle: "Product Manager",
    skills: ["Product Analytics", "Mixpanel", "Amplitude", "SQL"],
    experienceLevel: "Lead",
    skillFit: 99,
    experienceFit: 98,
    status: "Hired",
    appliedDate: "2023-10-10",
  },
  {
    id: "CAND-016",
    name: "Peter Wright",
    avatarUrl: "",
    email: "peter.w@example.com",
    jobTitle: "UX/UI Designer",
    skills: ["Interaction Design", "Motion Graphics", "After Effects"],
    experienceLevel: "Senior",
    skillFit: 35,
    experienceFit: 40,
    status: "Rejected",
    appliedDate: "2023-10-18",
  }
];

export const jobs: Job[] = [
  {
    id: "JOB-001",
    title: "Senior Frontend Developer",
    department: "Engineering",
    status: "Open",
    requiredSkills: ["React", "TypeScript", "Next.js", "GraphQL", "TailwindCSS"],
    requiredExperienceLevel: "Senior",
  },
  {
    id: "JOB-002",
    title: "Product Manager",
    department: "Product",
    status: "Open",
    requiredSkills: ["Agile", "JIRA", "Roadmapping", "User Research", "Market Research"],
    requiredExperienceLevel: "Senior",
  },
  {
    id: "JOB-003",
    title: "Data Scientist",
    department: "Data & Analytics",
    status: "On Process",
    requiredSkills: ["Python", "TensorFlow", "PyTorch", "SQL", "Machine Learning"],
    requiredExperienceLevel: "Mid-level",
  },
  {
    id: "JOB-004",
    title: "UX/UI Designer",
    department: "Design",
    status: "Open",
    requiredSkills: ["Figma", "Sketch", "Prototyping", "Design Systems", "User Flows"],
    requiredExperienceLevel: "Mid-level",
  },
  {
    id: "JOB-005",
    title: "Java Backend Developer",
    department: "Engineering",
    status: "Completed",
    requiredSkills: ["Java", "Spring Boot", "Microservices", "Kafka", "Hibernate"],
    requiredExperienceLevel: "Senior",
  },
  {
    id: "JOB-006",
    title: "Backend Engineer",
    department: "Engineering",
    status: "Open",
    requiredSkills: ["Node.js", "Python", "PostgreSQL", "Docker", "AWS", "Go"],
    requiredExperienceLevel: "Mid-level",
  },
];

export const newHires: NewHire[] = [
  {
    id: "HIRE-001",
    name: "David Kim",
    avatarUrl: "",
    jobTitle: "UX/UI Designer",
    hireDate: "2023-11-01",
    onboardingStatus: "On Track",
    tasks: [
      { id: "T1", name: "Complete HR Paperwork", status: "Completed" },
      { id: "T2", name: "Set up development environment", status: "Completed" },
      { id: "T3", name: "Meet the team", status: "In Progress" },
    ],
  },
  {
    id: "HIRE-002",
    name: "Olivia Hernandez",
    avatarUrl: "",
    jobTitle: "Product Manager",
    hireDate: "2023-11-05",
    onboardingStatus: "On Track",
    tasks: [
      { id: "T1", name: "Complete HR Paperwork", status: "Completed" },
      { id: "T2", name: "Equipment setup", status: "Completed" },
      { id: "T3", name: "Product roadmap overview", status: "Completed" },
    ],
  },
  {
    id: "HIRE-003",
    name: "Grace Lee",
    avatarUrl: "",
    jobTitle: "Junior Backend Engineer",
    hireDate: "2023-10-28",
    onboardingStatus: "At Risk",
    tasks: [
      { id: "T1", name: "Complete HR Paperwork", status: "Completed" },
      { id: "T2", name: "Set up development environment", status: "Not Started" },
      { id: "T3", name: "Intro to codebase session", status: "Not Started" },
    ],
  },
  {
    id: "HIRE-004",
    name: "Sam Wilson",
    avatarUrl: "",
    jobTitle: "Data Analyst",
    hireDate: "2023-11-10",
    onboardingStatus: "Delayed",
    tasks: [
      { id: "T1", name: "Complete HR Paperwork", status: "In Progress" },
      { id: "T2", name: "Access to data warehouse", status: "Not Started" },
      { id: "T3", name: "Team introduction", status: "Not Started" },
    ],
  },
];

export const hiringFunnelData = [
    { stage: 'Sourced', count: candidates.filter(c => c.status === 'Sourced').length, fill: 'var(--color-chart-1)' },
    { stage: 'Screening', count: candidates.filter(c => c.status === 'Screening').length, fill: 'var(--color-chart-2)' },
    { stage: 'Interview', count: candidates.filter(c => c.status === 'Interview').length, fill: 'var(--color-chart-3)' },
    { stage: 'Offer', count: candidates.filter(c => c.status === 'Offer').length, fill: 'var(--color-chart-4)' },
    { stage: 'Hired', count: candidates.filter(c => c.status === 'Hired').length, fill: 'var(--color-chart-5)' },
  ];
  
export const recentActivity = [
    {
      id: 1,
      candidateName: "Alana Vasquez",
      activity: "moved to Interview stage for Senior Frontend Developer.",
      time: "2 hours ago"
    },
    {
      id: 2,
      candidateName: "Frank Miller",
      activity: "was sourced for Java Backend Developer.",
      time: "5 hours ago"
    },
    {
      id: 3,
      candidateName: "Carla Rodriguez",
      activity: "received an offer for the Product Manager role.",
      time: "1 day ago"
    },
    {
      id: 4,
      candidateName: "Ben Carter",
      activity: "passed the initial screening.",
      time: "2 days ago"
    }
  ]
